version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: orion
      MYSQL_USER: fab
      MYSQL_PASSWORD_FILE: /run/secrets/database_password
    secrets:
      - database_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Back/src/main/resources/create_orion_db.sql:/docker-entrypoint-initdb.d/create_orion_db.sql

  backend:
    build: ./Back
    ports:
      - "3001:3001"
    networks:
      - app-network
    secrets:
      - database_url
      - database_username
      - database_password
      - jwt_key
      - cors_allowed_origins
    environment:
      - DATABASE_URL_FILE=/run/secrets/database_url
      - DATABASE_USERNAME_FILE=/run/secrets/database_username
      - DATABASE_PASSWORD_FILE=/run/secrets/database_password
      - JWT_KEY_FILE=/run/secrets/jwt_key
      - CORS_ALLOWED_ORIGINS_FILE=/run/secrets/cors_allowed_origins

  frontend:
    build: ./Front
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    expose:
      - "80"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
  database_url:
    file: ./secrets/database_url.txt
  database_username:
    file: ./secrets/database_username.txt
  database_password:
    file: ./secrets/database_password.txt
  jwt_key:
    file: ./secrets/jwt_key.txt
  cors_allowed_origins:
    file: ./secrets/cors_allowed_origins.txt

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
