version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: orion
      MYSQL_USER: project1_user1
      MYSQL_PASSWORD_FILE: /run/secrets/database_password
    secrets:
      - mysql_password
      - database_password
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Back/src/main/resources/create_orion_db.sql:/docker-entrypoint-initdb.d/create_orion_db.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: citizensyd/backend:latest
    ports:
      - "3001:3001"
    networks:
      - app-network
    secrets:
      - database_url
      - database_username
      - database_password
      - jwt_key
      - cors_allowed_origins
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    build: ./Front  # Le service frontend construit l'application Angular
    networks:
      - app-network
    volumes:
      - ./Front/dist/Front:/usr/share/nginx/html  # Copier les fichiers buildés dans Nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest  # Nginx pour servir le frontend et gérer les requêtes backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Configuration Nginx pour le reverse proxy et frontend
      - nginx_logs:/var/log/nginx
      - ./Front/dist/Front:/usr/share/nginx/html  # Serve les fichiers Angular statiques
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  mysql_password:
    external: true
  database_password:
    external: true
  database_url:
    external: true
  database_username:
    external: true
  jwt_key:
    external: true
  cors_allowed_origins:
    external: true

networks:
  app-network:
    driver: overlay

volumes:
  mysql_data:
  nginx_logs:
