version: '3.8'

services:
  mysql:
    image: mysql:8.4.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: project1_user1
      MYSQL_DATABASE: orion
      MYSQL_PASSWORD_FILE: /run/secrets/database_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    secrets:
      - mysql_password
      - database_password
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
#      - ./my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 3
    deploy:
         replicas: 1
         restart_policy:
          condition: on-failure

  backend:
    image: citizensyd/backend:v0.43
    environment:
      SPRING_PROFILES_ACTIVE: prod
      spring.profiles.active: prod
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - app-network
    secrets:
      - database_url
      - database_username
      - database_password
      - jwt_key
      - cors_allowed_origins
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 90s

  frontend:
    image: citizensyd/frontend:v0.06
    networks:
      - app-network
    depends_on:
      - mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    image: citizensyd/nginx-custom:v0.13
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
      placement:
        constraints: [ node.role == manager ]
    command: ["/wait-for-it.sh", "backend:3001", "--", "/wait-for-it.sh", "frontend:80", "--", "nginx", "-g", "daemon off;"]


secrets:
  mysql_password:
    external: true
  database_password:
    external: true
  database_url:
    external: true
  database_username:
    external: true
  jwt_key:
    external: true
  cors_allowed_origins:
    external: true

networks:
  app-network:
    driver: overlay

volumes:
  mysql_data:
  mysql_logs:
  nginx_logs:

