FROM mysql:8.4.2

# Copier les scripts d'initialisation SQL dans le répertoire approprié
#COPY ./scripts/init.sql /docker-entrypoint-initdb.d/

# Optionnel : copier des fichiers de configuration spécifiques de MySQL
#COPY ./my.cnf /etc/mysql/my.cnf

# Exposer les ports MySQL
EXPOSE 3306 33060
