FROM certbot/certbot:v2.11.0

### Copier les scripts nécessaires dans le conteneur
#COPY wait-for-it.sh /wait-for-it.sh
##
### Rendre les scripts exécutables
#RUN chmod +x /wait-for-it.sh
#
## Utiliser entrypoint.sh comme point d'entrée
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

